# Generated by Django 4.2 on 2023-04-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_lower_bound',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='price_suffix',
            field=models.CharField(choices=[('N', ''), ('S', 'за услугу'), ('H', 'за час'), ('U', 'за единицу'), ('D', 'за день'), ('MT', 'за месяц'), ('M2', 'за м2'), ('M', 'за м')], default='N', max_length=3),
        ),
    ]
