# Generated by Django 4.2 on 2023-04-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='identifier',
        ),
    ]
