# Generated by Django 4.2 on 2023-04-22 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_user_city_product_city'),
        ('app', '0006_remove_user_identifier'),
    ]

    operations = [
    ]
