# Generated by Django 4.2.3 on 2024-04-16 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_merge_20230422_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_suffix',
            field=models.CharField(choices=[('N', 'руб'), ('S', 'за услугу'), ('H', 'за час'), ('U', 'за единицу'), ('D', 'за день'), ('MT', 'за месяц'), ('M2', 'за м2'), ('M', 'за м')], default='N', max_length=3),
        ),
        migrations.CreateModel(
            name='ProductFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
